# START:neography
source 'http://rubygems.org'

gem 'neography', '~> 0.0.7',
  :git    => 'git://github.com/undees/neography.git',
  :branch => 'warbler'

gem 'jruby-openssl', '~> 0.7'
# END:neography

# START:sinatra
gem 'sinatra', '~> 1.1'
gem 'haml',    '~> 3.0'
# END:sinatra
