file 'performance.tsv' do
  sh <<HERE
curl -O http://download.freebase.com/datadumps\
/latest/browse/film/performance.tsv
HERE
end

desc 'Download movie data'
task :download => 'performance.tsv'

# START:import
desc 'Import movie data into Neo4j'
task :import do
# END:import
  start = Time.now
  print 'Importing (0% done, calculating remaining)'

  # START:import
  require 'lib/database'

  File.open('performance.tsv') do |f|
    db = Database.new

    f.gets # header
    f.each_line do |line|
      _, _, actor_name, movie_name = line.split "\t"
      next if actor_name.empty? || movie_name.empty?

      actor = db.find_or_create 'actor', actor_name
      movie = db.find_or_create 'movie', movie_name
      db.acted_in actor, movie
      # END:import

      complete  = f.pos.to_f / f.stat.size
      elapsed   = Time.now - start
      remaining = elapsed / complete - elapsed
      countdown = '%d:%02d' % [remaining / 60, remaining % 60]

      printf "\rImporting (%.02f%% done, %s remaining)      ",
      complete * 100,
      complete > 0.05 ? countdown : 'calculating'

      # START:import
    end
  end
end
# END:import

task :import => 'performance.tsv'
